### ISSUE TITLE
Sequence of execution of the following steps

### ISSUE THREAD

**Issue by Shiny128** [abhay97ps/Anomaly-Detection-in-Surveillance-Videos#11]
Hello 
I'm new to programming and I am unable to understand the execution steps to be followed to see the output . Please guide the sequence of execution in order to see the output

_Originally posted by @Shiny128 in https://github.com/abhay97ps/Anomaly-Detection-in-Surveillance-Videos/issues/3#issuecomment-472905123_

**Comment by draxler1** [comment]
Clone this repository to Pycharm or any other platform.
Install the required library Caffe, Tensorflow.

You need not change anything in repository.

Run driver.py. Try to solve the error or post here.

ALL THE BEST

**Comment by verissimomanoel** [comment]
The are some problems with the code indentation in the file Anomaly_NN.py, but I corrected this and when I tried to run the code I received the error below:
 
Traceback (most recent call last):
  File "Driver.py", line 51, in <module>
    train_model()
  File "Driver.py", line 18, in train_model
    train_NN(train_ano,train_norm,test_ano,test_norm,ano_width[125:],norm_width[125:])
  File "/home/noleak/Research/Anomaly-Detection-in-Surveillance-Videos/Anomaly_NN.py", line 113, in train_NN
    train_neural_network(x)
  File "/home/noleak/Research/Anomaly-Detection-in-Surveillance-Videos/Anomaly_NN.py", line 67, in train_neural_network
    anomaly_score = sess.run(prediction,feed_dict={x: batch_x})
  File "/home/noleak/anaconda3/envs/tfanomaly/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/noleak/anaconda3/envs/tfanomaly/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1149, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/noleak/anaconda3/envs/tfanomaly/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'map'

I tried to run this code with tensorflow-gpu 1.5 python 3.7. Can you help me?

**Comment by junaid340** [comment]
> 
> 
> The are some problems with the code indentation in the file Anomaly_NN.py, but I corrected this and when I tried to run the code I received the error below:
> 
> Traceback (most recent call last):
> File "Driver.py", line 51, in
> train_model()
> File "Driver.py", line 18, in train_model
> train_NN(train_ano,train_norm,test_ano,test_norm,ano_width[125:],norm_width[125:])
> File "/home/noleak/Research/Anomaly-Detection-in-Surveillance-Videos/Anomaly_NN.py", line 113, in train_NN
> train_neural_network(x)
> File "/home/noleak/Research/Anomaly-Detection-in-Surveillance-Videos/Anomaly_NN.py", line 67, in train_neural_network
> anomaly_score = sess.run(prediction,feed_dict={x: batch_x})
> File "/home/noleak/anaconda3/envs/tfanomaly/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
> run_metadata_ptr)
> File "/home/noleak/anaconda3/envs/tfanomaly/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1149, in _run
> np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
> File "/home/noleak/anaconda3/envs/tfanomaly/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray
> return array(a, dtype, copy=False, order=order)
> TypeError: float() argument must be a string or a number, not 'map'
> 
> I tried to run this code with tensorflow-gpu 1.5 python 3.7. Can you help me?

Hi, Im getting the same error. Did you solved it??
